#pragma once
#define NumAcceptConnectPort 0
#define NumAccessCheck 1
#define NumAccessCheckAndAuditAlarm 2
#define NumAccessCheckByType 3
#define NumAccessCheckByTypeAndAuditAlarm 4
#define NumAccessCheckByTypeResultList 5
#define NumAccessCheckByTypeResultListAndAuditAlarm 6
#define NumAccessCheckByTypeResultListAndAuditAlarmByHandle 7
#define NumAddAtom 8
#define NumAddBootEntry 9
#define NumAddDriverEntry 10
#define NumAdjustGroupsToken 11
#define NumAdjustPrivilegesToken 12
#define NumAlertResumeThread 13
#define NumAlertThread 14
#define NumAllocateLocallyUniqueId 15
#define NumAllocateUserPhysicalPages 16
#define NumAllocateUuids 17
#define NumAllocateVirtualMemory 18
#define NumApphelpCacheControl 19
#define NumAreMappedFilesTheSame 20
#define NumAssignProcessToJobObject 21
#define NumCallbackReturn 22
#define NumCancelDeviceWakeupRequest 23
#define NumCancelIoFile 24
#define NumCancelTimer 25
#define NumClearEvent 26
#define NumClose 27
#define NumCloseObjectAuditAlarm 28
#define NumCompactKeys 29
#define NumCompareTokens 30
#define NumCompleteConnectPort 31
#define NumCompressKey 32
#define NumConnectPort 33
#define NumContinue 34
#define NumCreateDebugObject 35
#define NumCreateDirectoryObject 36
#define NumCreateEvent 37
#define NumCreateEventPair 38
#define NumCreateFile 39
#define NumCreateIoCompletion 40
#define NumCreateJobObject 41
#define NumCreateJobSet 42
#define NumCreateKey 43
#define NumCreateMailslotFile 44
#define NumCreateMutant 45
#define NumCreateNamedPipeFile 46
#define NumCreatePagingFile 47
#define NumCreatePort 48
#define NumCreateProcess 49
#define NumCreateProcessEx 50
#define NumCreateProfile 51
#define NumCreateSection 52
#define NumCreateSemaphore 53
#define NumCreateSymbolicLinkObject 54
#define NumCreateThread 55
#define NumCreateTimer 56
#define NumCreateToken 57
#define NumCreateWaitablePort 58
#define NumDebugActiveProcess 59
#define NumDebugContinue 60
#define NumDelayExecution 61
#define NumDeleteAtom 62
#define NumDeleteBootEntry 63
#define NumDeleteDriverEntry 64
#define NumDeleteFile 65
#define NumDeleteKey 66
#define NumDeleteObjectAuditAlarm 67
#define NumDeleteValueKey 68
#define NumDeviceIoControlFile 69
#define NumDisplayString 70
#define NumDuplicateObject 71
#define NumDuplicateToken 72
#define NumEnumerateBootEntries 73
#define NumEnumerateDriverEntries 74
#define NumEnumerateKey 75
#define NumEnumerateSystemEnvironmentValuesEx 76
#define NumEnumerateValueKey 77
#define NumExtendSection 78
#define NumFilterToken 79
#define NumFindAtom 80
#define NumFlushBuffersFile 81
#define NumFlushInstructionCache 82
#define NumFlushKey 83
#define NumFlushVirtualMemory 84
#define NumFlushWriteBuffer 85
#define NumFreeUserPhysicalPages 86
#define NumFreeVirtualMemory 87
#define NumFsControlFile 88
#define NumGetContextThread 89
#define NumGetDevicePowerState 90
#define NumGetPlugPlayEvent 91
#define NumGetWriteWatch 92
#define NumImpersonateAnonymousToken 93
#define NumImpersonateClientOfPort 94
#define NumImpersonateThread 95
#define NumInitializeRegistry 96
#define NumInitiatePowerAction 97
#define NumIsProcessInJob 98
#define NumIsSystemResumeAutomatic 99
#define NumListenPort 100
#define NumLoadDriver 101
#define NumLoadKey 102
#define NumLoadKey2 103
#define NumLoadKeyEx 104
#define NumLockFile 105
#define NumLockProductActivationKeys 106
#define NumLockRegistryKey 107
#define NumLockVirtualMemory 108
#define NumMakePermanentObject 109
#define NumMakeTemporaryObject 110
#define NumMapUserPhysicalPages 111
#define NumMapUserPhysicalPagesScatter 112
#define NumMapViewOfSection 113
#define NumModifyBootEntry 114
#define NumModifyDriverEntry 115
#define NumNotifyChangeDirectoryFile 116
#define NumNotifyChangeKey 117
#define NumNotifyChangeMultipleKeys 118
#define NumOpenDirectoryObject 119
#define NumOpenEvent 120
#define NumOpenEventPair 121
#define NumOpenFile 122
#define NumOpenIoCompletion 123
#define NumOpenJobObject 124
#define NumOpenKey 125
#define NumOpenMutant 126
#define NumOpenObjectAuditAlarm 127
#define NumOpenProcess 128
#define NumOpenProcessToken 129
#define NumOpenProcessTokenEx 130
#define NumOpenSection 131
#define NumOpenSemaphore 132
#define NumOpenSymbolicLinkObject 133
#define NumOpenThread 134
#define NumOpenThreadToken 135
#define NumOpenThreadTokenEx 136
#define NumOpenTimer 137
#define NumPlugPlayControl 138
#define NumPowerInformation 139
#define NumPrivilegeCheck 140
#define NumPrivilegeObjectAuditAlarm 141
#define NumPrivilegedServiceAuditAlarm 142
#define NumProtectVirtualMemory 143
#define NumPulseEvent 144
#define NumQueryAttributesFile 145
#define NumQueryBootEntryOrder 146
#define NumQueryBootOptions 147
#define NumQueryDebugFilterState 148
#define NumQueryDefaultLocale 149
#define NumQueryDefaultUILanguage 150
#define NumQueryDirectoryFile 151
#define NumQueryDirectoryObject 152
#define NumQueryDriverEntryOrder 153
#define NumQueryEaFile 154
#define NumQueryEvent 155
#define NumQueryFullAttributesFile 156
#define NumQueryInformationAtom 157
#define NumQueryInformationFile 158
#define NumQueryInformationJobObject 159
#define NumQueryInformationPort 160
#define NumQueryInformationProcess 161
#define NumQueryInformationThread 162
#define NumQueryInformationToken 163
#define NumQueryInstallUILanguage 164
#define NumQueryIntervalProfile 165
#define NumQueryIoCompletion 166
#define NumQueryKey 167
#define NumQueryMultipleValueKey 168
#define NumQueryMutant 169
#define NumQueryObject 170
#define NumQueryOpenSubKeys 171
#define NumQueryOpenSubKeysEx 172
#define NumQueryPerformanceCounter 173
#define NumQueryQuotaInformationFile 174
#define NumQuerySection 175
#define NumQuerySecurityObject 176
#define NumQuerySemaphore 177
#define NumQuerySymbolicLinkObject 178
#define NumQuerySystemEnvironmentValue 179
#define NumQuerySystemEnvironmentValueEx 180
#define NumQuerySystemInformation 181
#define NumQuerySystemTime 182
#define NumQueryTimer 183
#define NumQueryTimerResolution 184
#define NumQueryValueKey 185
#define NumQueryVirtualMemory 186
#define NumQueryVolumeInformationFile 187
#define NumQueueApcThread 188
#define NumRaiseException 189
#define NumRaiseHardError 190
#define NumReadFile 191
#define NumReadFileScatter 192
#define NumReadRequestData 193
#define NumReadVirtualMemory 194
#define NumRegisterThreadTerminatePort 195
#define NumReleaseMutant 196
#define NumReleaseSemaphore 197
#define NumRemoveIoCompletion 198
#define NumRemoveProcessDebug 199
#define NumRenameKey 200
#define NumReplaceKey 201
#define NumReplyPort 202
#define NumReplyWaitReceivePort 203
#define NumReplyWaitReceivePortEx 204
#define NumReplyWaitReplyPort 205
#define NumRequestDeviceWakeup 206
#define NumRequestPort 207
#define NumRequestWaitReplyPort 208
#define NumRequestWakeupLatency 209
#define NumResetEvent 210
#define NumResetWriteWatch 211
#define NumRestoreKey 212
#define NumResumeProcess 213
#define NumResumeThread 214
#define NumSaveKey 215
#define NumSaveKeyEx 216
#define NumSaveMergedKeys 217
#define NumSecureConnectPort 218
#define NumSetBootEntryOrder 219
#define NumSetBootOptions 220
#define NumSetContextThread 221
#define NumSetDebugFilterState 222
#define NumSetDefaultHardErrorPort 223
#define NumSetDefaultLocale 224
#define NumSetDefaultUILanguage 225
#define NumSetDriverEntryOrder 226
#define NumSetEaFile 227
#define NumSetEvent 228
#define NumSetEventBoostPriority 229
#define NumSetHighEventPair 230
#define NumSetHighWaitLowEventPair 231
#define NumSetInformationDebugObject 232
#define NumSetInformationFile 233
#define NumSetInformationJobObject 234
#define NumSetInformationKey 235
#define NumSetInformationObject 236
#define NumSetInformationProcess 237
#define NumSetInformationThread 238
#define NumSetInformationToken 239
#define NumSetIntervalProfile 240
#define NumSetIoCompletion 241
#define NumSetLdtEntries 242
#define NumSetLowEventPair 243
#define NumSetLowWaitHighEventPair 244
#define NumSetQuotaInformationFile 245
#define NumSetSecurityObject 246
#define NumSetSystemEnvironmentValue 247
#define NumSetSystemEnvironmentValueEx 248
#define NumSetSystemInformation 249
#define NumSetSystemPowerState 250
#define NumSetSystemTime 251
#define NumSetThreadExecutionState 252
#define NumSetTimer 253
#define NumSetTimerResolution 254
#define NumSetUuidSeed 255
#define NumSetValueKey 256
#define NumSetVolumeInformationFile 257
#define NumShutdownSystem 258
#define NumSignalAndWaitForSingleObject 259
#define NumStartProfile 260
#define NumStopProfile 261
#define NumSuspendProcess 262
#define NumSuspendThread 263
#define NumSystemDebugControl 264
#define NumTerminateJobObject 265
#define NumTerminateProcess 266
#define NumTerminateThread 267
#define NumTestAlert 268
#define NumTraceEvent 269
#define NumTranslateFilePath 270
#define NumUnloadDriver 271
#define NumUnloadKey 272
#define NumUnloadKey2 273
#define NumUnloadKeyEx 274
#define NumUnlockFile 275
#define NumUnlockVirtualMemory 276
#define NumUnmapViewOfSection 277
#define NumVdmControl 278
#define NumWaitForDebugEvent 279
#define NumWaitForMultipleObjects 280
#define NumWaitForSingleObject 281
#define NumWaitHighEventPair 282
#define NumWaitLowEventPair 283
#define NumWriteFile 284
#define NumWriteFileGather 285
#define NumWriteRequestData 286
#define NumWriteVirtualMemory 287
#define NumYieldExecution 288
#define NumCreateKeyedEvent 289
#define NumOpenKeyedEvent 290
#define NumReleaseKeyedEvent 291
#define NumWaitForKeyedEvent 292
#define NumQueryPortInformationProcess 293
#define NumGetCurrentProcessorNumber 294
#define NumWaitForMultipleObjects32 295
#define NumWow64AllocateVirtualMemory64 296
#define NumWow64ReadVirtualMemory64 297
#define NumWow64WriteVirtualMemory64 298